package kotlinx.coroutines.internal;

/* compiled from: CoroutineExceptionHandlerImpl.common.kt */
public final class ExceptionSuccessfullyProcessed extends Exception {

    /* renamed from: h  reason: collision with root package name */
    public static final ExceptionSuccessfullyProcessed f15582h = new ExceptionSuccessfullyProcessed();

    private ExceptionSuccessfullyProcessed() {
    }
}
